preset: laravel

risky: true

disabled:
  - concat_without_spaces
  - length_ordered_imports
enabled:
  - concat_with_spaces
  - alpha_ordered_imports

finder:
  not-name:
    - "index.php"
    - "server.php"
  exclude:
    - "tests"
    - "vendor"
